// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using patternsUserSetting.UserSettingSetup;

#nullable disable

namespace patternsUserSetting.Migrations
{
    [DbContext(typeof(UserSettingDataContext))]
    [Migration("20260405154545_idempotencyKeyTable")]
    partial class idempotencyKeyTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ClassLibrary.HiddenAccount", b =>
                {
                    b.Property<Guid>("HiddenAccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("HiddenAccountId");

                    b.ToTable("hiddenAccounts");
                });

            modelBuilder.Entity("ClassLibrary.IdempotencyKeyDB", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StatusCode")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("idempotencyKeys");
                });

            modelBuilder.Entity("ClassLibrary.UserSettingDB", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDarkMode")
                        .HasColumnType("boolean");

                    b.HasKey("UserId");

                    b.ToTable("userSettings");
                });
#pragma warning restore 612, 618
        }
    }
}
