spring:
  application:
    name: currency

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:29092}

  datasource:
    url: jdbc:postgresql://localhost:5432/patterns_currency
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml

server:
  port: 8084
  forward-headers-strategy: framework

springdoc:
  swagger-ui:
    path: /swagger
  api-docs:
    path: /v3/api-docs
  cache:
    disabled: true

currency:
  list:
    url: https://api.fxratesapi.com/latest
    processed:
      - id: 643
        name: "Российский рубль"
        charCode: RUB
      - id: 840
        name: "Доллар США"
        charCode: USD
      - id: 156
        name: "Китайский юань"
        charCode: CNY
      - id: 398
        name: "Казахстанский тенге"
        charCode: KZT
      - id: 0
        name: "Биткоин"
        charCode: BTC
