spring:
  application:
    name: patterns-gateway

  datasource:
    url: jdbc:postgresql://localhost:5432/patterns_gateway
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: identity-server
              uri: ${services.identity-server.url:http://identity-server:5001}
              predicates:
                - Path=/identity/**
              filters:
                - StripPrefix=1
                - AddRequestHeader=X-Forwarded-Prefix, /identity
                - name: CircuitBreaker
                  args:
                    name: identityServerCb
                    fallbackUri: forward:/fallback/identity-server
                    statusCodes:
                      - 500

            - id: patterns-users
              uri: ${services.patterns-users.url:http://patterns-users:8080}
              predicates:
                - Path=/users/**
              filters:
                - StripPrefix=1
                - AddRequestHeader=X-Forwarded-Prefix, /users
                - name: CircuitBreaker
                  args:
                    name: patternsUsersCb
                    fallbackUri: forward:/fallback/patterns-users
                    statusCodes:
                      - 500

            - id: patterns-user-setting
              uri: ${services.patterns-user-setting.url:http://patterns-user-setting:8080}
              predicates:
                - Path=/settings/**
              filters:
                - StripPrefix=1
                - AddRequestHeader=X-Forwarded-Prefix, /settings
                - name: CircuitBreaker
                  args:
                    name: patternsUserSettingCb
                    fallbackUri: forward:/fallback/patterns-user-setting
                    statusCodes:
                      - 500

            - id: account-service
              uri: ${services.account-service.url:http://account-service:8082}
              predicates:
                - Path=/core/**
              filters:
                - StripPrefix=1
                - AddRequestHeader=X-Forwarded-Prefix, /core
                - name: CircuitBreaker
                  args:
                    name: accountServiceCb
                    fallbackUri: forward:/fallback/account-service
                    statusCodes:
                      - 500

            - id: credit-service
              uri: ${services.credit-service.url:http://credit-service:8081}
              predicates:
                - Path=/credit/**
              filters:
                - StripPrefix=1
                - AddRequestHeader=X-Forwarded-Prefix, /credit
                - name: CircuitBreaker
                  args:
                    name: creditServiceCb
                    fallbackUri: forward:/fallback/credit-service
                    statusCodes:
                      - 500

            - id: transfers-service
              uri: ${services.transfers-service.url:http://transfers-service:8083}
              predicates:
                - Path=/transfers/**
              filters:
                - StripPrefix=1
                - AddRequestHeader=X-Forwarded-Prefix, /transfers
                - name: CircuitBreaker
                  args:
                    name: transfersServiceCb
                    fallbackUri: forward:/fallback/transfers-service
                    statusCodes:
                      - 500

            - id: currency-service
              uri: ${services.currency-service.url:http://currency-service:8084}
              predicates:
                - Path=/currency/**
              filters:
                - StripPrefix=1
                - AddRequestHeader=X-Forwarded-Prefix, /currency
                - name: CircuitBreaker
                  args:
                    name: currencyServiceCb
                    fallbackUri: forward:/fallback/currency-service
                    statusCodes:
                      - 500

            - id: monitoring-service
              uri: ${services.monitoring-service.url:http://monitoring-service:8086}
              predicates:
                - Path=/monitoring/**
              filters:
                - StripPrefix=1
                - AddRequestHeader=X-Forwarded-Prefix, /monitoring
                - name: CircuitBreaker
                  args:
                    name: monitoringServiceCb
                    fallbackUri: forward:/fallback/monitoring-service
                    statusCodes:
                      - 500

server:
  port: 8085
  forward-headers-strategy: framework

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true

unstable:
  enabled: false

resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        minimum-number-of-calls: 10
        failure-rate-threshold: 70
        wait-duration-in-open-state: 15s
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
    instances:
      identityServerCb:
        base-config: default
      patternsUsersCb:
        base-config: default
      patternsUserSettingCb:
        base-config: default
      accountServiceCb:
        base-config: default
      creditServiceCb:
        base-config: default
      transfersServiceCb:
        base-config: default
      currencyServiceCb:
        base-config: default
      monitoringServiceCb:
        base-config: default
