spring:
  application:
    name: Credit Service

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:29092}

  datasource:
    url: jdbc:postgresql://localhost:5432/patterns_credit
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml

server:
  port: 8081
  forward-headers-strategy: framework

springdoc:
  swagger-ui:
    path: /swagger
    oauth2-redirect-url: ${SWAGGER_OAUTH2_REDIRECT_URL:http://localhost:8081/swagger-ui/oauth2-redirect.html}
    oauth:
      client-id: ${SWAGGER_CLIENT_ID:api_swagger_credit}
      use-pkce-with-authorization-code-grant: true
      scopes: ${SWAGGER_OAUTH_SCOPES:SampleAPI}
  api-docs:
    path: /v3/api-docs
  cache:
    disabled: true

app:
  kafka:
    take-credit-topic: 00_take_credit
  security:
    oauth2:
      authorization-url: ${SWAGGER_AUTHORIZATION_URL:https://localhost:5001/connect/authorize}
      token-url: ${SWAGGER_TOKEN_URL:https://localhost:5001/connect/token}
      scope: ${SWAGGER_OAUTH_SCOPE:SampleAPI}
      scope-description: ${SWAGGER_OAUTH_SCOPE_DESCRIPTION:Sample API - full access}
