spring:
  application:
    name: Credit Service

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:29092}

  datasource:
    url: jdbc:postgresql://localhost:5432/patterns_credit
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml

server:
  port: 8081

app:
  kafka:
    take-credit-topic: 00_take_credit
