spring:
  application:
    name: transfers

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:29092}

server:
  port: 8083
  forward-headers-strategy: framework

springdoc:
  swagger-ui:
    path: /swagger
    oauth:
      client-id: ${SWAGGER_CLIENT_ID:api_swagger_transfers}
      use-pkce-with-authorization-code-grant: true
      scopes: ${SWAGGER_OAUTH_SCOPES:SampleAPI}
  api-docs:
    path: /v3/api-docs
  cache:
    disabled: true

app:
  security:
    oauth2:
      authorization-url: ${SWAGGER_AUTHORIZATION_URL:https://localhost:5001/connect/authorize}
      token-url: ${SWAGGER_TOKEN_URL:https://localhost:5001/connect/token}
      scope: ${SWAGGER_OAUTH_SCOPE:SampleAPI}
      scope-description: ${SWAGGER_OAUTH_SCOPE_DESCRIPTION:Sample API - full access}

kafka:
  url: ${KAFKA_URL:localhost:29092}
  group: "transfers-service"

  consumer:
    transfer-request: 00_transfer_request

  provider:
    transfer-assignment: 00_transfer_assignment

accounts:
  master-account-number: 0000-0000-0000-0000
