spring:
  application:
    name: transfers

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:29092}

server:
  port: 8083

kafka:
  url: ${KAFKA_URL:localhost:29092}
  group: "transfers-service"

  consumer:
    transfer-request: 00_transfer_request

  provider:
    transfer-assignment: 00_transfer_assignment

accounts:
  master-account-number: 0000-0000-0000-0000
