spring:
  application:
    name: account

  datasource:
    url: jdbc:postgresql://localhost:5432/patterns_core_account
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml

server:
  port: 8082

master-bank:
  account-number: 0000-0000-0000-0000
  money: 1000000000
  user-id: 00000000-0000-0000-0000-000000000000

kafka:
  url: localhost:9092
  group: ""

  consumer:
    ban-users: 00_ban_users_core
